---
output: html_document
---



## Reality Perception and Manipulation

\scriptsize

**Makowski, D.**, Lau, Z. J., Pham, T., Ayache, J., Sperduti, M., Sumich, A., Heym, N. & Chen, S., A. (*under review*). Psychological Determinants of the Susceptibility to COVID-19 Fake News.

**Makowski, D.**, Lau, Z. J., Pham, T., Boyce, W. P. \& Chen, S. A. (2021). [A Parametric Framework to Generate Visual Illusions using Python](https://dominiquemakowski.github.io/publication/makowski2021parametric/makowski2021parametric.pdf). *Perception*, 50(11), 950-965.

**Makowski, D.**, Pham, T., Lau, Z. J., Raine, A., & Chen, S. H. (2021). [The Structure of Deception: Validation of the Lying Profile Questionnaire](https://dominiquemakowski.github.io/publication/makowski2021structure/makowski2021structure.pdf). *Current Psychology*, 1-16.

**Makowski, D.**, Sperduti, M., Pelletier, J., Blondé, P., La Corte, V., Arcangeli, M., Zalla, T., Lemaire, S., Dokic, J., Nicolas, S., & Piolino, P. (2019). [Phenomenal, Bodily and Brain Correlates of Fictional Reappraisal as an Implicit Emotion Regulation Strategy](https://dominiquemakowski.github.io/publication/makowski2019phenomenal/makowski2019phenomenal.pdf). *Cognitive, Affective, & Behavioral Neuroscience*, 19(4), 1-21.

**Makowski, D.**\*, Sperduti, M.\*, Nicolas, S. & Piolino, P. (2017). ["*Being there*" and remembering it: Presence improves Memory Encoding](https://dominiquemakowski.github.io/publication/makowski2017being/makowski2017being.pdf). *Consciousness & Cognition, 53*, 194–202.

Sperduti, M.\*, **Makowski, D.**\*, Arcangeli, M., Wantzen, P., Zalla, T., Lemaire, S., Dokic, J., Pelletier, J. & Piolino, P. (2017). [The Distinctive Role of Executive Functions in Implicit Emotion Regulation](https://dominiquemakowski.github.io/publication/sperduti2017distinctive/sperduti2017distinctive.pdf). *Acta Psychologica, 173*, 13-20.

Tuena, C., Serino, S., Gaston-Bellegarde, A., Orriols, E., **Makowski, D.**, Riva, G. & Piolino, P. (2017). [How Virtual Embodiment Affects Episodic Memory Functioning: a Proof-of-Concept Study](https://dominiquemakowski.github.io/publication/tuena2017virtual/tuena2017virtual.pdf), *Annual Review of Cybertherapy and Telemedicine*, 15, 93-107.

Sperduti, M.\*, Arcangeli, M.\*, **Makowski, D.**, Wantzen, P., Zalla, T., Lemaire, S., Dokic, J., Pelletier, J. \& Piolino, P. (2016). [The paradox of fiction: Emotional response toward fiction and the modulatory role of self-relevance](https://dominiquemakowski.github.io/publication/sperduti2016paradox/sperduti2016paradox.pdf). *Acta psychologica*, 165, 53-59.


\normalsize

## Neurophysiology, Emotion Regulation and Interoceptive Processes

\scriptsize

Pham, T., Lau, Z. J., Chen, S. A., & **Makowski, D.** (*under review*). [Unveiling the Structure of Heart Rate Variability (HRV) Indices: A Data-driven Meta-clustering Approach](https://psyarxiv.com/mwa6x/). *PsyXarkiv*.

Lau, Z. J.\*, Pham, T.\*, Chen, S. A., & **Makowski, D.** (2022). [Brain Entropy, Fractal Dimensions and Predictability: A Review of Complexity Measures for EEG in Healthy and Neuropsychiatric Populations](https://onlinelibrary.wiley.com/doi/abs/10.1111/ejn.15800). *European Journal of Neuroscience, 56*(7), 5047-5069.

**Makowski, D.**, Te, A. S., Pham, T., Lau, Z. J., & Chen, S. H. (2022). [The Structure of Chaos: An Empirical Comparison of Fractal Physiology Complexity Indices Using Neurokit2](https://www.mdpi.com/1099-4300/24/8/1036). *Entropy, 24*(8), 1036.

Pham, T., Lau, Z. J., Chen, S. H. A., & **Makowski, D.** (2021). [Heart Rate Variability in Psychology: A Review of HRV Indices and an Analysis Tutorial](https://www.mdpi.com/1424-8220/21/12/3998). *Sensors, 21*(12), 3998.

**Makowski, D.**, Pham, T., Lau, Z. J., Brammer, J. C., Lespinasse, F., Pham, H., Schötzel, C., & Chen, S. A. (2021). [NeuroKit2: A Python Toolbox for Neurophysiological Signal Processing](https://dominiquemakowski.github.io/publication/makowski2021neurokit/makowski2021neurokit.pdf). *Behavior Research Methods*, 1-8.

**Makowski, D.**, Sperduti, M., Blondé, P., Nicolas, S., & Piolino, P. (2019). [The heart of cognitive control: Cardiac phase modulates processing speed and inhibition](https://dominiquemakowski.github.io/publication/makowski2019heart/makowski2019heart.pdf). *Psychophysiology, 57*(3).

**Makowski, D.**, Sperduti, M., Lavallée, S., Nicolas, S., & Piolino, P. (2019). [Adaptation and Validation of a Short French Version of the Affective Style Questionnaire](https://dominiquemakowski.github.io/publication/makowski2019adaptation/makowski2019adaptation.pdf). *International Journal of Cognitive Therapy, 13*(2), 146–158.

**Makowski, D.**\*, Sperduti, M.\*, Lavallée, S., Nicolas, S. & Piolino, P. (2019). [Dispositional mindfulness attenuates the emotional attentional blink](https://dominiquemakowski.github.io/publication/makowski2019dispositional/makowski2019dispositional.pdf). *Consciousness & Cognition, 67*, 16–25.

**Makowski, D.**, Sperduti, M., Blanchet, S., Nicolas, S. & Piolino, P. (2015). [Régulation Emotionnelle face au Déclin Cognitif dans le Vieillissement : Un Faux Paradoxe ? | Emotion regulation and the cognitive decline in aging: beyond the paradox](https://dominiquemakowski.github.io/publication/makowski2015emotion/makowski2015emotion.pdf). *Gériatrie et Psychologie Neuropsychiatrie du Vieillissement*, 13(3), 301-8.

\normalsize



## Statistics

\scriptsize

Patil, I., **Makowski, D.**, Ben-Shachar, M. S., Wiernik, B. M., Bacher, E., & Lüdecke, D. (2022). [datawizard: An R Package for Easy Data Preparation and Statistical Transformations](https://joss.theoj.org/papers/10.21105/joss.04684). *Journal of Open Source Software, 7*(78), 4684.

Lüdecke, D., Patil, I., Ben-Shachar, M., Wiernik, B., Waggoner, P., & **Makowski, D.** (2021). [see: An R Package for Visualizing Statistical Models](https://joss.theoj.org/papers/10.21105/joss.03393). *Journal of Open Source Software, 6*(64), 3393.

Lüdecke, D., Ben-Shachar, M., Patil, I., Waggoner, P., & **Makowski, D.** (2021). [performance: An R Package for Assessment, Comparison and Testing of Statistical Models](https://joss.theoj.org/papers/10.21105/joss.03139). *Journal of Open Source Software, 6*(60), 3139.

Ben-Shachar, M. S., Lüdecke, D., & **Makowski, D.** (2020). [effectsize: Estimation of Effect Size Indices and Standardized Parameters](https://joss.theoj.org/papers/10.21105/joss.02815). *Journal of Open Source Software, 5*(56), 2815.

Lüdecke, D., Ben-Shachar, M. S., Patil, I., & **Makowski, D.** (2020). [parameters: Extracting, Computing and Exploring the Parameters of Statistical Models using R](https://joss.theoj.org/papers/10.21105/joss.02445). *Journal of Open Source Software, 5*(53), 2445.

**Makowski, D.**, Ben-Shachar, M. S., Patil, I., & Lüdecke, D. (2020). [Methods and Algorithms for Correlation Analysis in R](https://joss.theoj.org/papers/10.21105/joss.02306). *Journal of Open Source Software, 5*(51), 2306.

**Makowski, D.**, Ben-Shachar, M. S., Chen, S. H., & Lüdecke, D. (2019). [Indices of Effect Existence and Significance in the Bayesian Framework](https://dominiquemakowski.github.io/publication/makowski2019indices/makowski2019indices.pdf). *Frontiers in Psychology, 10*.

**Makowski, D.**, Ben-Shachar, M., & Lüdecke, D. (2019). [bayestestR: Describing effects and their uncertainty, existence and significance within the Bayesian framework](https://joss.theoj.org/papers/10.21105/joss.01541). *Journal of Open Source Software, 4*(40), 1541.

Lüdecke, D., Waggoner, P., & **Makowski, D.** (2019). [insight: A unified interface to access information from model objects in R](https://joss.theoj.org/papers/10.21105/joss.01412). *Journal of Open Source Software*, 4(38), 1412.

**Makowski, D.** (2018). [The psycho Package: An Efficient and Publishing-Oriented Workflow for Psychological Science](https://dominiquemakowski.github.io/publication/makowski2018psycho/makowski2018psycho.pdf). *Journal of Open Source Software, 3*(22), 470.

\normalsize

## Miscellaneous

\scriptsize

Lee, H., Jacquot, A., **Makowski, D.**, Arcangeli, M., Dokic, J., Piolino, P., & Sperduti, M. (2023). [Beauty is in the eye of the beholder: Evidence from a common mnemonic advantage between aesthetics judgement and self-reference](https://dominiquemakowski.github.io/publication/lee2023beauty/lee2023beauty.pdf). *Psychology of Consciousness: Theory, Research, and Practice*.

Kovarski, K., Dos Reis, J., Chevais, C., Hamel, A., **Makowski, D.**, & Sperduti, M. (2022). [Movie editing influences spectators' time perception](https://www.nature.com/articles/s41598-022-23992-2). *Scientific Reports, 12*(1), 20084.

Blondé, P., Sperduti, M., **Makowski, D.**, & Piolino, P. (2022). [Bored, distracted, and forgetful: The impact of mind wandering and boredom on memory encoding](https://journals.sagepub.com/doi/abs/10.1177/17470218211026301). *Quarterly Journal of Experimental Psychology, 75*(1), 53-69.

Blondé, P., **Makowski D.**, Sperduti, M., & Piolino, P. (2020). [In Medio Stat Virtus: intermediate levels of mind wandering improve episodic memory encoding in a virtual environment](https://dominiquemakowski.github.io/publication/blonde2020medio/blonde2020medio.pdf). *Psychological Research, 85*(4), 1613–1625.

<!-- TODO: fix page number -->
Girardeau, J. C., Blondé, P., **Makowski D.**, Abram, M., Piolino, P., & Sperduti, M. (2020). [The impact of state and dispositional mindfulness on prospective memory: A virtual reality study](https://dominiquemakowski.github.io/publication/girardeau2020impact/girardeau2020impact.pdf). *Consciousness and Cognition, 81*, 102920.

**Makowski, D.**, Dutriaux, L. (2017). [Neuropsydia.py: A Python Module for Creating Experiments, Tasks and Questionnaires](https://joss.theoj.org/papers/10.21105/joss.00259), *Journal of Open Source Software, 2*(19), 259.

Sperduti, M., Armougum, A., **Makowski, D.**, & Piolino, P. (2017). [Interaction between attentional systems and episodic memory encoding: the impact of conflict on binding of information](https://dominiquemakowski.github.io/publication/sperduti2017interaction/sperduti2017interaction.pdf), *Experimental Brain Research*, 235(12), 3553-3560.

Nicolas, S., & **Makowski, D**. (2017). [Centenaire Ribot (I). La réception de l'oeuvre de Théodule Ribot chez l'éditeur Ladrange (1870-1873)](https://dominiquemakowski.github.io/publication/nicolas2017centenaire/nicolas2017centenaire.pdf). *Bulletin de Psychologie*, 70(3), 163-178.

Sperduti, M., **Makowski, D.**, Blondé, P. & Piolino, P. (2017). [Meditation and successful aging: can meditative practices counteract age-related cognitive decline?](https://dominiquemakowski.github.io/publication/sperduti2017meditation/sperduti2017meditation.pdf), *Gériatrie et Psychologie Neuropsychiatrie du Vieillissement*, 15(2), 205-13.

Nicolas, S., & **Makowski, D**. (2016). [Can mental fatigue be measured by Weber's compass? Alfred Binet's answer on the value of aesthesiometry (tactile sensitivity) as an objective measure of mental fatigue](https://dominiquemakowski.github.io/publication/nicolas2016can/nicolas2016can.pdf). *European Yearbook of the History of Psychology*, 2, 11-46.

Sperduti, M., **Makowski, D.**, & Piolino, P. (2016). [The protective role of long-term meditation on the decline of the executive component of attention in aging: a preliminary cross-sectional study](https://dominiquemakowski.github.io/publication/sperduti2016protective/sperduti2016protective.pdf). *Aging, Neuropsychology, and Cognition*, 23(6), 691-702.

\normalsize



# Communications

## General Audience / Media Coverage

\footnotesize

- Invited on the "Learning Bayesian Statistics" Podcast, `r link("\\#55 Neuropsychology, Illusions \\& Bending Reality, with Dominique Makowski", "https://www.learnbayesstats.com/episode/55-neuropsychology-illusions-bending-reality-dominique-makowski")`. 01 Feb 2022, learnbayesstats.com
- Speaker at the Pint of Science, `r link("Back to the Matrix : pilule bleue ou rouge ?", "https://pintofscience.com/")`. 16 May 2018, Paris, France.
- Invited to participate in a Public Debate, `r link("Art \\& science discussion on sensory illusions", "https://facts2017.u-bordeaux.fr/FESTIVAL/Programme/Agenda-2017/Rencards-du-savoir-Les-illusions-sensorielles.html")`. 24 November 2017, Bordeaux, France.
- Published article in magazine, `r link("Neuroanatomie de la réalité : quand le réel n'est plus", "https://biblineuropsy.com/2016/04/19/les-yeux-brouilles/")`. 2016, Les yeux brouillés, 1, 48-55.
- Featured on National TV, `r link("The effect of violent images on the brain and body", "https://www.youtube.com/watch?v=ihGs1V9kz4w")`. 2015, Testé sous contrôle médical, France 4
- Research Featured in Online journal, `r link("”Avengers, l'ère d’Ultron” en 3D : aussitôt vu, aussitôt oublié ?", "(http://blog.francetvinfo.fr/actu-cine/2015/05/07/avengers-lere-dultron-en-3d-aussitot-vu-aussitot-oublie.html")` 2015, francetvinfos.fr

\normalsize


## Talks

\tiny

<!-- \begin{center}\textit{2018}\end{center} -->

**Co-organizer** (2021). *La recherche aux temps de la COVID*, `r link("1ère journée du COllaborative COgnitive Science", "https://sites.google.com/view/les-cocos/")`, 29 November, Online.

**Makowski, D.**, Sperduti, M., Nicolas, S. & Piolino, P. (2018). *Interindividual Determinants of Emotion Regulation through Fiction*. 2ème Congrès Francophone de TCC, 14-16 June, Geneva, Switzerland.

**Makowski, D.** (2018, *invited*). *How Reality can Modulate Memory and Emotions*. CRPCPO's monthly seminar, 23 March, Amiens, France.

**Makowski, D.**, Sperduti, M., Nicolas, S. & Piolino, P. (2018). *Engagement in Fiction as an Altered State of Consciousness*. 6th Mind, Brain & Body Symposium, 15-16 March, Berlin, Germany.



<!-- \begin{center}\textit{2017}\end{center} -->

**Makowski, D.**, Sperduti, M., Nicolas, S. & Piolino, P. (2017). *Vers la thérapie neurocognitive ? L’apport des neurosciences affectives dans la TCC*. 45ème congrès de l’AFTCC, 14-16 December, Paris, France.

Sperduti, M., **Makowski, D.** & Piolino, P. (2017). *The Role of Self-Relevance and Interindividual Variability in Executive Functions in Implicit Emotion Regulation*. International Society for the Study of Interindividual Differences (ISSID), 24-28 July, Warsaw, Poland.

**Makowski, D.**, Sperduti, M. & Piolino, P. (2017). *The Distinctive Effect of Emotion Regulation andMindfulness on Attentional Capture*. 1ère Journée Scientifique des Jeunes Chercheurs du Centre de Recherches sur la Cognition et l’Apprentissage, 8 June, Poitiers, France.

<!-- \begin{center}\textit{2016}\end{center} -->

**Makowski, D.**, Sperduti, M. & Piolino, P. (2016).*”Being there” and Remembering it: Presence en-hances Encoding in Memory*. International Congress On Memory (ICOM), 17-22 July, Budapest, Hungary.

**Makowski, D.**, Sperduti, M. & Piolino, P. (2016). *The Sense of Reality as a feature of proto-Consciousness, its Alteration and Generation induced by Fictional Worlds*. Literary States of Consciousness, 2 June, Paris, France.

**Makowski, D.**, Sperduti, M. & Piolino, P. (2016). *Does Mindfulness ability differently affect Implicit and Explicit Emotion Regulation?* 2nd International Conference on Mindfulness (ICM), 11-15 May, Roma, Italy.

Sperduti, M., **Makowski, D.** & Piolino, P. (2016). *Does mindfulness enhance interoception? Dissociation between different interoceptive abilities*. 2nd International Conference on Mindfulness, 11-15 May, Roma, Italy.

<!-- \begin{center}\textit{2015}\end{center} -->

**Makowski, D.**, Sperduti, M. & Piolino, P. (2015). *Bon et Mauvais Régulateurs Emotionnels: Un Rôle Spécifique de l’Inhibition ?* 56è Congrès National de la Société Française de Psychologie (SFP), 2-4 September, Strasbourg, France.

**Makowski, D.**, Sperduti, M., Pelletier, J. & Piolino, P. (2015). *Régulation émotionnelle et Self Control : De la recherche Fondamentale à l’Application Clinique*. 1er Congrès Francophone de TCC, 27-29 May, Lyon, France.

<!-- \begin{center}\textit{2014}\end{center} -->

**Makowski, D.**, Sperduti, M., Arcangeli, M., Pelletier, J. & Piolino, P. (2014). *From Philosophy to the Rehabilitation of Psychiatric Patients: Fiction/Reality, Emotion et Cognitive Control*. Journée d’hiver de l’IUPDP, 19 December, Boulogne-Billancourt, France.

**Makowski, D.**, Sperduti, M. & Piolino, P. (2014). *L’émotion face à la fiction : l’étude de patients schizophrènes éclaire le paradoxe de la fiction*. 27 June, Fête de la Recherche, Boulogne-Billancourt,France.

<!-- \begin{center}\textit{2013}\end{center} -->

**Makowski, D.**, & Rossi, S. (2013). `r link("\\textit{Le jugement esthétique chez l’enfant}", "https://www.youtube.com/watch?v=Hvs7t5G_dLM")`. Journées Neurosciences, Esthétique, et Complexité, 28 September, Paris, France.


\normalsize

## Posters

\tiny

<!-- \begin{center}\textit{2022}\end{center} -->
**Makowski, D.,** Lau, Z. J., Pham, T., Te, A. S., & Chen, S. A. (2022). *Fractal dimension of EEG activity is linked to distinct facets of resting‑state cognition*. 28th Annual Meeting of the Organization for Human Brain Mapping (OHBM), 19-23 June, Glasgow, Scotland.

**Makowski, D.,** Lau, Z. J., Pham, T., Te, A. S., & Chen, S. A. (2022). *A Closer Look at Cardiac Contraction and the Effect of Cardiac Timing on Cognitive Control*. 28th Annual Meeting of the Organization for Human Brain Mapping (OHBM), 19-23 June, Glasgow, Scotland.

<!-- \begin{center}\textit{2021}\end{center} -->

Lau, Z. J., Pham, T., Boyce, W. P., Chen, S. A., & **Makowski, D.** (2021). `r link("\\textit{A Parametric Framework to Generate Visual Illusions using Python}", "https://youtu.be/uptP_NxEHaM")`. 43rd European Conference on Visual Perception, 22-27 Aug. Online.

<!-- \begin{center}\textit{2016}\end{center} -->

**Makowski, D.**, Sperduti, M. \& Piolino, P. (2016). *Régulation Emotionnelle, pleine-conscience et bien-être : Interactions et implication dans les troubles de l’humeur*. Journée d’hivers de la Société de Neuropsychologie de Langue Française, 5 December, Paris, France.

Blondé, P., Sperduti, M., **Makowski, D.** \& Piolino, P. (2016). *Le rôle des réseaux attentionnels sur l’encodage en mémoire épisodique dans le cadre du vieillissement et de sa variabilité interindividuelle liée aux traits de pleine conscience*. Journée d’hivers de la Société de Neuropsychologie de Langue Française, 5 December, Paris, France.

**Makowski, D.**, Sperduti, M. \& Piolino, P. (2016).
*I know it’s not real... what does it change?* nCPN day, 16 September, Paris, France.

<!-- \begin{center}\textit{2015}\end{center} -->

**Makowski, D.**, Sperduti, M. \& Piolino, P. (2015). *"J’avais l’impression d’y être" : Sentiment de présence et encodage en mémoire autobiographique*. Journée d’hiver de la Société de Neuropsychologie de Langue Française, 5 December, Paris, France.

Sperduti, M., **Makowski, D.** \& Piolino, P. (2015). *Interaction entre systèmes attentionnels et encodage en mémoire épisodique*. Journée d’hivers de la Société de Neuropsychologie de Langue Française, 5 December, Paris, France.

**Makowski, D.**, Sperduti, M., Arcangeli, M., Pelletier, J. \& Piolino, P. (2015). *I know it’s not real... what does it change?* 12e colloque de la Société des Neurosciences, 19-22 May, Montpellier, France.

<!-- \begin{center}\textit{2014}\end{center} -->

**Makowski, D.**, Sperduti, M., Arcangeli, M., Pelletier, J. \& Piolino, P. (2014) *Emotion Regulation by fiction is related to cognitive inhibition.* Journée d’hiver de la Société de Neuropsychologie de Langue Française, 5 December, Paris, France.

Sperduti, M., **Makowski, D.**, Vialatte, F. \& Piolino, P. (2014). *The decline of Autobiographical Memory in aging, inhibition and the cingulate cortex: an activation and resting state fMRI study.* Journées d’Etudes du Vieillissement, 15-16 September, Caen, France.

Sperduti, M., **Makowski, D.** \& Piolino, P. (2014). *The protective role of meditation on the cognitive decline in aging: a cross-sectional study*. Journées d’Etudes du Vieillissement, 15-16 September, Caen, France.

<!-- \begin{center}\textit{2013}\end{center} -->

**Makowski, D.**, Sperduti, M., Arcangeli, M., Pelletier, J. \& Piolino, P. (2013). *QUID du paradoxe de l’émotion face à la fiction ? Nouvelles données physiologiques comparant la réponse émotionnelle à des scènes réelles ou fictionnelles*. Journées de l’IUPDP, 19 December, Boulogne-Billancourt, France.

\normalsize
