---
output: 
  github_document:
    toc: false
    fig_width: 10.08
    fig_height: 6
tags: [r, reports]
vignette: >
  \usepackage[utf8]{inputenc}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---


```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  tidy.opts = list(width.cutoff = 80),
  tidy = TRUE,
  fig.path = "img/",
  fig.width = 10,
  comment = "#>",
  dpi = 300
)
options(knitr.kable.NA = '', digits = 2, width = 80)

library(dplyr)
library(ggplot2)
```

# My CV (WIP)


- My CV can be downloaded [**from here**](dominiquemakowski.github.io/cv/).
- More information can be found on [my website](https://dominiquemakowski.github.io).

The steps to pull the data from Google scholar and render the CV are the following:

```{r eval=FALSE}
# 1. Update scientific impact data
source("make_data_impact.R")

# 4. Render CV (and CV-data)
rmarkdown::render('C:/Dropbox/PERSO/CV/DominiqueMakowski_CV.Rmd',  encoding = 'UTF-8')
```


## Figures 

```{r echo = FALSE, fig.height=6, fig.width=10, fig.align="center"}
load("data/data_scholar.Rdata")

source("functions.R")

plot_impact(data_scholar)
```
